### PR TITLE
Alfresco 6

### PR DESCRIPTION
**Pull request by douglascrp**
Changes to make the addon compatible with Alfresco 6:
Alfresco SDK upgraded to 4.0-beta1;
Updated itext dependencies to latest version;
Changes to make java code compatible with the new itext version.

### CODE REVIEW

**Comment by douglascrp** [comment]
This PR would solve the problems for #51 and #53

**Comment by digcatcom** [comment]
so have tested this pull request, and it allows me to build amps, which can be installed onto 6.0.7-ga.
couple of small things, I added
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
to the properties of the repo pom, to get rid of a warning on compile.

also when starting up alfresco after installing, we see ERROR on the transformers its creating for Itext.

content.transformer.iText.TextToPdf.extensions.txt.pdf.priority=50
content.transformer.iText.TextToPdf.extensions.txt.pdf.supported=true
content.transformer.iText.TextToPdf.extensions.csv.pdf.priority=50
content.transformer.iText.TextToPdf.extensions.csv.pdf.supported=true
content.transformer.iText.TextToPdf.extensions.xml.pdf.priority=50
content.transformer.iText.TextToPdf.extensions.xml.pdf.supported=true
content.transformer.iText.TiffToPdf.extensions.tiff.pdf.priority=50
content.transformer.iText.TiffToPdf.extensions.tiff.pdf.supported=true

not sure whether the addon should automatically add these to alfresco-global.properties or not ?

**Comment by renatofritola** [comment]
Hello, do you have any forecast for the merge? I am waiting for this improvement to be able to use the addon in alfresco 6.

Thank you.

**Comment by digcatcom** [comment]
> Hello, do you have any forecast for the merge? I am waiting for this improvement to be able to use the addon in alfresco 6.
> 
> Thank you.

Hi renatofritola

Have you tried the PR on a test system?  we need more testing to ensure the PR is good and can be merged so any feedback welcome.

**Pull request merged**
